---
title: "January 2025 Notes"
format: html
editor: visual
---

## Work notes

### 15 Feb 2026

I have determined that two folders that were processed on 26 December 2026, the day the NoCo Wild hard drive failed, did not make it to upload on the Zooniverse. Those are:

-   C089_SD035

-   C091_SD005

Both got uploaded to AWS when processed, but neither have Processed folders. Need to run the scripts to resize them and then get ready for zooniverse. I will prepare them for zooniverse upload right now.

Got both folders added to Zooniverse. I also created a manifest for folder C041_SD013 (see 5 Feb 2026 below) and uploaded it, with each image as a separate event due to the timestamp problem, so now all images from summer and fall 2025 should be on the Zooniverse.

I also uploaded the images remaining from 2024, but left them "turned off" on the Zooniverse so they will not be available to ID until the current (summer/fall 2025) images are all classified.

### 5 Feb 2026

I think we have just about got all of the images from summer and fall 2025 up onto the zooniverse for classification (esp with the batch I just uploaded now, see immediately below).

I need to check to see that all of the AWS uploads are logged on the master spreadsheet. I also need to check master spreadsheet to make sure that all zooniverse uploads are logged there.

Preparing another batch of images for upload to the zooniverse while I process more files from Summer 2025.

Folders processed for upload today include:

-   C051_SD161 - 46 images

-   C061_SD007 - 29 images

-   C066_SD035 - 806 images

-   C067_SD038 - 237 images

-   C068_SD003 - 66 images

-   C069_SD064 - 147 images

-   C082_SD089 - 60 images

-   C082_SD105 - 75 images

This leaves out folder C041_SD013. In that folder all images were assigned the same time stamp by the camera, so I'm going to have to create the manifest for those images by hand. It has 162 images. I may have to just feed 1 image per event so that we can at least get species diversity data from the files.

### 4 Feb 2026

Preparing another batch of images for upload to the zooniverse while I process more files from Summer 2025.

Some folders are lower priority, since they are not from Aidan and Liz's work.

These I put copies of in a folder called "Summer 2024" for a zooniverse upload that should be done in the next few days and turned off until summer/fall 2025 images are IDd.

-   C036_SD018 - 2903 images; summer 2024

-   C021_SD025 - 156 images; summer 2024

-   C047_SD040 - 132 images; fall 2024

-   C048_SD035 - 87 images; fall 2024

-   C052_SD084 - 450 images; fall 2024

-   C047_SD011 - 513 images; fall 2024

-   C048_SD064 - 258 images; fall 2024

-   C066_SD095 - 264 images; summer 2024

-   C064_SD006 - 45 images; summer 2024

Separately, working on a different zooniverse upload with summer/fall 2025 images. Next batch includes the following folders. I prepared this batch and began uploading them to the zooniverse today.

-   C059_SD034 - 144 images;

-   C059_SD104 - 153 images;

-   C062_SD036 - 27 images;

-   C063_SD077 - 3905 images;

-   C064_SD162 - 45 images

-   C065_SD090 - 271 images

### 3 Feb 2026

Continued prepping files that I started with yesterday for upload to the Zooniverse platform. All of the folders that I processed on 2 Feb were uploaded to the Zooniverse today.

Next I'm working on data processing so that we can get more images up onto the zooniverse ASAP.

### 2 Feb 2026

Worked on preparing more files for zooniverse upload. Batch to include the following folders from 2024 Game camera images:

-   C021_SD065 - 116 images

-   C038_SD103 - 123 images

-   C056_SD041 - 1854 images

-   C066_SD019 - 1014 images

-   C052_SD005 - 663 images

-   C047_SD060 - 606 images

-   C060_SD089 - 12 images; no images other than camera deployment (ELB) and appear to be from Fall 2024. Appears to be deployment C0340. Images are on Zooniverse, so will add to AWS as well. Needs to be done.

Note that folder C051_SD162 was empty. There are images in the corresponding "Raw" folder with incorrect date/times that have not been properly renamed using our scripts.

### 30 Jan 2026

Zooniverse volunteers are insane! They already classified all of the images through the "Is there an animal?" workflow so I need to put up more images!

Worked on preparing more files for zooniverse upload. Batch to include the following folders from 2024 Game camera images:

-   C052_SD113 - 645 images

-   C061_SD107 - 366 images

-   C068_SD101 - 1326 images

-   C054_SD110 - 741 images

-   C041_SD042 - 147 images

-   C027_SD017 - 474 images

-   C066_SD111 - 132 images

-   C069_SD086 - 129 images

-   C047_SD112 - 537 images

-   C043_SD012 - 1341 items

And since it is the weekend and we want to take advantage of lots of volunteers, I'm preparing a second set of images to upload, including the following:

-   C058_SD009 - 1815 images

-   C086_SD100 - 180 images

-   C067_SD109 - 276 images

-   C050_SD031 - 282 images

-   C052_SD032 - 66 images

-   C050_SD062 - 778 images

-   C048_SD033 - 24 images

-   C047_SD011_2 - 210 images

-   C043_SD021 - 639 images

-   C038_SD042 - 147 images

-   C038_SD018 - 39 images

-   C036_SD074 - 132 images

-   C035_SD040 - 156 images

-   C032_SD025 - 54 images

-   C028_SD001 - 81 images

-   C027_SD026 - 91 images

### 29 Jan 2026

Worked on preparing more files for zooniverse upload. Batch to include the following folders from 2024 Game camera images:

-   C059_SD060 - 89 images

-   C056_SD087 - 207 images

-   C054_SD075 - 198 images

-   C065_SD091 - 222 images

-   C087_SD102 - 153 images

-   C064_SD041 - 252 images

-   C028_SD014 - 104 images

-   C084_SD019 - 354 images

-   C063_SD026 - 150 images

-   C036_SD040 - 242 images

-   C021_SD084 - 495 images

-   C062_SD025 - 159 images

-   C051_SD108 - 1734 images

These were uploaded to the zooniverse as batch named Z-29-Jan-2026-upload.

### 28 Jan 2026

My work on Monday resulted in a problem with my code when trying to prepare a 3rd batch of images for the zooniverse. Today I'm working on debugging that code so that we can continue the work.

The code breaks when running the `assignEvents()` function that I wrote several years ago. I suspect the error has to do with generation of an NA in the Interval column of the data frame, so that when assigning events based on the time interval between images, the code doesn't know how to handle the NA and stops.

The problem appears to be that for some reason, the Exif data reports NA for the DateTimeOriginal field for a few photos. I need to modify the `assignEvents()` function to handle those cases.

In the case of this problem, it looks like when I generated the exif data using exiftool in the terminal, for some reason it skipped 2 files - they have incomplete exif data. So I'm going to start by running that tool again to see if I get the same problem.

Same problem arose: for 2 files, exiftool did not generate DateTimeOriginal in exif data file. I looked up both files and got their exif data manually, and each file seems to be corrupted - cannot get exif data and cannot open images.

So, removed 2 files from those to be uploaded to zoonverse:

C082_SD036_20250930115204_IMG_0710.JPG

C082_SD036_20250930150909_folder2_IMG_0050.JPG

Also updated function `assignEvents`. Current version now gives error message if it finds and images lacking DateTimeOriginal and returns row numbers with issues as well as unchanged original DF.

Function `assignEventsOld()` is the prior version of the function that did not address NA in DateTimeOriginal.

Now that it is all working, pushed the next upload to zooniverse as Z-28-Jan-2026-upload using the exif file Z-28-Jan-2026-upload-exif to generate the manifest.

### 26 Jan 2026

#### Preparing files for upload to zooniverse.

Batch to include the following folders from 2025 Game camera images:

-   C048_SD034 - 993 images

-   C048_SD115 - 114 images

-   C049_SD017 - 60 images

-   C050_SD064 - 607 images

-   C050_SD109 - 205 images

-   C052_SD077 -45 images

-   C054_SD104 - 61 images

-   C056_SD003 - 300 images

-   C058_SD007 - 228 images

-   C059_SD013 - 165 images

-   C059_SD116 - 204 images

I copied all of these images to a folder called "Z-26-Jan-2026-upload" and used that folder for generating an exif file. All of these were uploaded today.

#### Preparing 2nd set to upload for today also.

Added images from the following folders:

-   C061_SD102 - 70 images

-   C062_SD113 - 495 images

-   C064_SD032 - 84 images

-   C065_SD011 - 740 images

-   C066_SD107 - 1761 images

-   C067_SD013 - 87 images

-   C067_SD083 - 534 images

-   C068_SD091 - 378 images

These were all loaded to zooniverse as 26-Jan-2026-2nd-upload

#### Preparing 3rd upload

I made another folder that I called "next-upload" and copied images from the following folders:

-   C069_SD040 - 507 images

-   C082_SD036 - 1725 images

-   C083_SD012 - 522 images

-   C083_SD102 - 84 images

-   C085_SD074 - 204 images

-   C086_SD065 - 1674 images

-   C086_SD105 - 114 images

-   C087_SD086 - 213 images

-   C999_SD019 - 219 images

I got all of these images moved to a folder called "next-upload" and then started running the code in `PreZooniversePrep.Rmd` but when I got to line 108 `Exif<-assignEvents(Exif) #no threshold passed, using default of 60 seconds` I received the following error message:\

::: callout-note
Error in if(!cond\[i\]) ev \<- ev else ev \<- ev+1:\
missing value where TRUE/FALSE needed
:::

So I need to diagnose. Note that the exif file for these images in in the parent directory to the folder in a file called `Z-26-Jan-2026-upload-3-exif.csv` as I will need it to diagnose.

Next time, break into the file and see if I can figure that out.

### 22 Jan 2026

Preparing files for upload to zooniverse.

Batch to include the following folders from 2025 Game camera images:

-   C035_SD062 - 1707 images

-   C035_SD117 - 57 images

-   C038_SD014 - 75 images

-   C038_SD075 -98 images

-   C043_SD025 - 69 images

-   C043_SD033 - 1508 images

-   C047_SD089 - 183 images

I copied all of these images to a folder called "Z-22-Jan-2026-upload" and used that folder for generating an exif file.

### Managing Zooniverse IDs

Digging in again after quite a hiatus. The code starting with `Parse files` below is reproduced exactly from the April-2024.Rmd file.

Let's take stock of where where are in terms of getting images classified properly. These are the workflows, including name, number, and version numbers, present in the "master" classification file through 15 Feb 2024:

+--------------------------+-----------------+--------------------------------------------------+-----------------------------------------------+
| Workflow Name            | Workflow Number | Workflow Version(s)                              | Status                                        |
+==========================+=================+==================================================+===============================================+
| Workflow 1               | 9599            | 73.7, 98.10, 100.12, 118.13, 120. 15             | Testing zooniverse                            |
+--------------------------+-----------------+--------------------------------------------------+-----------------------------------------------+
| Workflow 1               | 9599            | 121.16                                           | Nothing useful - in "checked" folder          |
+--------------------------+-----------------+--------------------------------------------------+-----------------------------------------------+
| Workflow 1               | 9599            | 123.17                                           | **Need to process folder**                    |
+--------------------------+-----------------+--------------------------------------------------+-----------------------------------------------+
| Workflow 1.1             | 12161           | 2.2                                              | Testing zooniverse                            |
+--------------------------+-----------------+--------------------------------------------------+-----------------------------------------------+
| Workflow 1.1             | 12161           | 3.3, 5.5                                         | Nothing useful - in "checked" folder          |
+--------------------------+-----------------+--------------------------------------------------+-----------------------------------------------+
| Workflow 1.1             | 12161           | 6.5                                              | **Need to process folder**                    |
+--------------------------+-----------------+--------------------------------------------------+-----------------------------------------------+
| Team Workflow 1.1        | 12477           | 1.10                                             | Testing zooniverse folder                     |
+--------------------------+-----------------+--------------------------------------------------+-----------------------------------------------+
| Is there an animal - old | 16675           | 12.18, 12.21, 13.23, 14.24, 15.24                | ???                                           |
+--------------------------+-----------------+--------------------------------------------------+-----------------------------------------------+
| Species identification   | 16695           | 2.20, 3.30, 5.40, 6.40, 7.50, 8.60, 9.70, 10.80, | 2.2 - 10.8, 22.1 in Testing zooniverse folder |
+--------------------------+-----------------+--------------------------------------------------+-----------------------------------------------+
| Species identification   | 16695           | 22.10, 13.30                                     |                                               |
+--------------------------+-----------------+--------------------------------------------------+-----------------------------------------------+
| Species identification   | 16695           | 11.8, 29.1                                       | **Need to process folder**                    |
+--------------------------+-----------------+--------------------------------------------------+-----------------------------------------------+
| Species ID internal      | 21244           | 13.30                                            | **Need to process folder**                    |
+--------------------------+-----------------+--------------------------------------------------+-----------------------------------------------+
| Is there an animal?      | 21527           | 2.90, 2.11, 2.14, 2.20                           | Not in classification file                    |
+--------------------------+-----------------+--------------------------------------------------+-----------------------------------------------+

: Status of image classifications by workflow\

## Hard drive error

31 Dec 2025

The external hard drive on which we keep all of the NoCo Wild images appears to be failing. Fortunately, I have a daily time machine backup on that drive. The last backup was on 26 Dec 2025. I am currently restoring all of the files from that backup to a new external hard drive, but am uncertain if any files were lost until the file transfer is complete. I will also need to re-tune time machine to back up the new external drive. Very frustrating, but thank goodness it looks like almost all of the data is backed up. Also appreciaton and thanks to Brett for working out a backup system on AWS. A good sabattical challenge is going to be to get all of the files correctly organized and onto s3.

### Checking status of subject sets

16 Dec 2025

Worked on code to take the subjects download from a zooniverse project and get a summary of which subject sets have been completed so it is easy to tell what to do next.

## Status of image classifications by workflow

### 5 June 2025

Continued working on `Code/PostZooniverse/3_Consensus_picks/4.merge_consensus_picks.qmd` to begin merging files.

wrote two helper functions as described.

### 4 June 2025 afternoon

Taking stock of where things are at. Building a table with locations of the files we need to combine to get the overall species identifications for all of the camera trap data to date. I am not including workflows related to "Is there an animal" or related to Humans:

Thus, not including workflows 16675, 21527

+------------------------------------+-----------------+--------------------------------------------------+-----------------------------------------------------------+
| Workflow Name                      | Workflow Number | Workflow Version(s)                              | Classification files with species ID                      |
+====================================+=================+==================================================+===========================================================+
| Workflow 1                         | 9599            | 73.7, 98.10, 100.12, 118.13, 120. 15             |                                                           |
+------------------------------------+-----------------+--------------------------------------------------+-----------------------------------------------------------+
| Workflow 1                         | 9599            | 121.16                                           |                                                           |
+------------------------------------+-----------------+--------------------------------------------------+-----------------------------------------------------------+
| Workflow 1                         | 9599            | 123.17                                           | NoCoW_class-15-Feb-2024-wfn9599_wfv123.17_assigned.csv    |
|                                    |                 |                                                  |                                                           |
|                                    |                 |                                                  | NoCoW_class-15-Feb-2024-wfn9599_wfv123.17_checked.csv     |
|                                    |                 |                                                  |                                                           |
|                                    |                 |                                                  | wkfl_9599_123.17_lastones_new.csv                         |
+------------------------------------+-----------------+--------------------------------------------------+-----------------------------------------------------------+
| Workflow 1.1                       | 12161           | 2.2                                              |                                                           |
+------------------------------------+-----------------+--------------------------------------------------+-----------------------------------------------------------+
| Workflow 1.1                       | 12161           | 3.3, 5.5                                         |                                                           |
+------------------------------------+-----------------+--------------------------------------------------+-----------------------------------------------------------+
| Workflow 1.1                       | 12161           | 6.5                                              | NoCoW_class-15-Feb-2024-wfn12161_wfv6.5_assigned.csv      |
|                                    |                 |                                                  |                                                           |
|                                    |                 |                                                  | NoCoW_class-15-Feb-2024-wfn12161_wfv6.5_checklist.csv     |
|                                    |                 |                                                  |                                                           |
|                                    |                 |                                                  | NoCoW_class-15-Feb-2024-wfn12161_wfv6.5_lastones_new.csv  |
+------------------------------------+-----------------+--------------------------------------------------+-----------------------------------------------------------+
| Team Workflow 1.1                  | 12477           | 1.10                                             |                                                           |
+------------------------------------+-----------------+--------------------------------------------------+-----------------------------------------------------------+
| Species identification             | 16695           | 2.20, 3.30, 5.40, 6.40, 7.50, 8.60, 9.70, 10.80, |                                                           |
+------------------------------------+-----------------+--------------------------------------------------+-----------------------------------------------------------+
| Species identification             | 16695           | 22.10, 13.30                                     |                                                           |
+------------------------------------+-----------------+--------------------------------------------------+-----------------------------------------------------------+
| Species identification             | 16695           | 11.8                                             | NoCoW_class-15-Feb-2024-wfn16695_wfv11.8_assigned.csv     |
|                                    |                 |                                                  |                                                           |
|                                    |                 |                                                  | NoCoW_class-15-Feb-2024-wfn16695_wfv11.8_lastones_new.csv |
+------------------------------------+-----------------+--------------------------------------------------+-----------------------------------------------------------+
| Species identification             | 16695           | 29.1                                             | NoCoW_class-15-Feb-2024-wfn16695_wfv29.1_assigned.csv     |
|                                    |                 |                                                  |                                                           |
|                                    |                 |                                                  | NoCoW_class-15-Feb-2024-wfn16695_wfv29.1_checked.csv      |
|                                    |                 |                                                  |                                                           |
|                                    |                 |                                                  | NoCoW_class-15-Feb-2024-wfn16695_wfv29.1_lastones_new.csv |
+------------------------------------+-----------------+--------------------------------------------------+-----------------------------------------------------------+
| Species ID internal                | 21244           | 13.30                                            | NoCoW_class-15-Feb-2024-wfn21244_wfv13.3_assigned.csv     |
|                                    |                 |                                                  |                                                           |
|                                    |                 |                                                  | NoCoW_class-15-Feb-2024-wfn21244_wfv13.3_lastones_new.csv |
+------------------------------------+-----------------+--------------------------------------------------+-----------------------------------------------------------+
| Species ID and Species ID internal | 16695 and 21244 | 11.8, 13.3                                       | wfv11.8_wfv13.3_have_nas.csv                              |
+------------------------------------+-----------------+--------------------------------------------------+-----------------------------------------------------------+

Remember that it is possible there are subject IDS that are identified in more than one workflow. Also remember that once this headache is all set, we can just extract later data and process it all together, without so many workflow changes.

Started working on `Code/PostZooniverse/3_Consensus_picks/4.merge_consensus_picks.qmd` to begin merging files.

### 4 June 2025 morning

Looking over files getting ready to put them together with Aidan and Liz. NoCoW_class-15-Feb-2024-wfn16695_wfv11.8_lastones_new has a problem in that all of the choices aren image numbers are NA. Need to go back into the code and figure out how that happened.

Looks like I took care of this with the file called wf11.8_wfv13.3_have_nas.csv. So ok.

### 9 May 2025

Trying to wrap up checking files. Worked on checking images in "wf 11.8_wfv13.3_have_nas.csv". Finished. Should now be able to merge all these files with final species IDs.

### 1 May 2025

Picked up with "check_nas.qmd" from 30 April. Saved new checklist file called "wf 11.8_wfv13.3_have_nas.csv" in `Output/PostZooniverse/Consensus/By workflow` and this is the file I will check the final classification and then merge with the rest of the consensus files.

Worked on checking images in "wf 11.8_wfv13.3_have_nas.csv" and got through a bit more than half.

### 30 April 2025

Investigating the reason that the files:

NoCoW_class-15-Feb-2024-wfn21244_wfv13.3_lastones_new.csv

NoCoW_class-15-Feb-2024-wfn16695_wfv11.8_lastones_new.csv

have so many NAs. See file called "check_nas.qmd" in Code/PostZooniverse/Error checking

Didn't finish. Pick up with "check_nas.qmd" next time.

### 29 April 2025

Finished NoCoW_class-15-Feb-2024-wfn21244_wfv13.3_lastones_new.csv - first row is a subject id with NA for image numbers. Still need to address that. Also need to address why NoCoW_class-15-Feb-2024-wfn16695_wfv11.8_lastones_new.csv has many NAs. That needs to be checked.

### 22 April 2025

Happy Earth Day!

Continuing where I left off yesterday. Finished NoCoW_class-15-Feb-2024-wfn12161_wfv6.5_lastones_new.csv. There appears to be an issue with NoCoW_class-15-Feb-2024-wfn16695_wfv11.8_lastones_new.csv - many NAs. That needs to be checked. Started on NoCoW_class-15-Feb-2024-wfn16695_wfv29.1_lastones_new.csv and finished it.

Started NoCoW_class-15-Feb-2024-wfn21244_wfv13.3_lastones_new.csv - first row is a subject id with NA for image numbers, like what is see in NoCoW_class-15-Feb-2024-wfn16695_wfv11.8_lastones_new.csv. Need to go back and check that. But working on file. Start here next time.

-   [ ] Check on NoCoW_class-15-Feb-2024 wfn16695_wfv11.8_lastones_new.csv - many NAs

-   [ ] Check why first row of NoCoW_class-15-Feb-2024-wfn21244_wfv13.3_lastones_new.csv as all image numbers are NA

### 21 April 2025

Continuing where I left off on 15 April 2025. Worked on NoCoW_class-15-Feb-2024-wfn12161_wfv6.5_lastones_new.csv. Continue with this file when I start up again. But I'm getting really close!

### 15 April 2025

Continuing where I left off on 3 April 2025. Worked on NoCoW_class-15-Feb-2024-wfn12161_wfv6.5_lastones_new.csv. Continue with this file when I start up again.

### 3 April 2025

Continuing where I left off on 28 March 2025. Worked on NoCoW_class-15-Feb-2024-wfn12161_wfv6.5_lastones_new.csv. Continue with this file when I start up again.

### 28 March 2025

Continuing where I left off on 24 March 2025. Worked on NoCoW_class-15-Feb-2024-wfn12161_wfv6.5_lastones_new.csv

### 24 March 2025

Picking up from 19 March activity. Doing image ID for those events in the "Last ones" .csv files.

### 19 March 2025

-   Going over images in the wkfl_9599_123.17_lastones_new.csv. Finished that; made sure that the workflow 9599 version 123.17 had 3 files in "By Workflow" folder. These are the three that should be joined to get final species list.

-   Next created corrected "last ones" file for workflow 12161 version 6.5. Went through and did this for each workflow.

### 17 March 2025

-   All files from the 15-Feb-2024 classification have been identified. Now I need code that merges the different files so that I can get the complete list of species identified at each camera event.

    -   Also, need code to randomly select events to check classifications and get a % correct based on what I go manually check

    -   Code for merging IDs needs to also join to code about images (time stamps) and cameras so that we can look at location and time information, and also so that we can assess trapping effort at each camera.

    -   Started on new file in Code/PostZooniverse/3_Consensus_picks/ called `4.merge_consensus_picks.Qmd`

    -   I realized that there was a mistake in the code in `3.determine_consensus_picks.Rmd` such that it was not saving the summary file of the last ones to check (the summary file is the one that is formatted like those in the Assigned and Checklist folders with each unique subject ID and it's associated images but not all of the many columns.

        -   Fixed the code today so that it saves the proper file, and saved the correct file for workflow number 9599 version number 123.17. Need to do the other workflows associated with the NoCoW_class-15-Feb-2024 classification file.

### 25 Feb 2025

-   Working on NoCoW_class-15-Feb-2024-wfn12161_wfv6.5_checklist.csv in the `By workflow` folder to confirm species ID by manually looking at photos on hard drive. Finished going through this file.

-   Now all of the files from the 15-Feb-2024 classification download from zooniverse have been identified.

-   Next is to join them all into one single file! Start that next time I work

### 20 Feb 2025

-   Working on NoCoW_class-15-Feb-2024-wfn12161_wfv6.5_checklist to confirm species ID by manually looking at photos on hard drive. Added a column to indicate the file path to the image, since these images are very old and don't follow the renaming system that Brett and I implemented.

-   Worked on that file for several hours with still more to go. Saved in the `By workflow` folder as `NoCoW_class-15-Feb-2024-wfn12161_wfv6.5_checklist.csv`. Start here again when you come back to the project.

### 30 Jan 2025

-   Working on NoCoW_class-15-Feb-2024-wfn12161_wfv6.5_checklist to confirm species ID by manually looking at photos on hard drive. Added a column to indicate the file path to the image, since these images are very old and don't follow the renaming system that Brett and I implemented.

-   Worked on that file for several hours with still more to go. Saved in the `By workflow` folder as `NoCoW_class-15-Feb-2024-wfn12161_wfv6.5_checklist.csv`. Start here again when you come back to the project.

### Parse files

I downloaded the 'master' classification file on 15 Feb 2024. I wrote a new script (./Code/PostZooniverse/1_Parse_and_Flatten_files/1.Parse_workflows.Rmd) that takes that classification file and subdivides it into the set of all possible workflows and workflow versions, each collected into its own .csv file and each with a metadata file. These are stored in (./Output/PostZooniverse/DFs).

### Flatten Files

I then took each of those files and flattened it, using the code in (./Code/PostZooniverse/1_Parse_and_Flatten_files/2.Flatten_Species_IDs.Rmd). I have not yet dealt with the "Is there an animal" workflows.

I put each flattened file in `./Output/PostZooniverse/Flattened/Species_ID`.

Those files that were clearly zooniverse "test runs" for different workflows (with only up to about 50 events and typically a single classification per event) I moved to a subfolder in that directory called `Testing zooniverse` where they sit, but where I do not need to work with them any further.

I moved the others into a folder called `Check` in the same subdirectory.

I went through all of the files in the `Check` directory using the file `./Code/PostZooniverse/2_Check classifications` and either moved the files into another subdirectory called `Checked` that need no further work because they don't have meaningful data. Those that have data that needs analysis I moved into a subdirectory called `need to process`. On April 4, 2024, this folder contains 5 data files of flattened classifications along with the metadata file for each for a total of 10 files in the subdirectory.

### Determine consensus picks

Next, I opened the file `./Code/PostZooniverse/3_Consensus_picks/3.determine_consensus_picks.Rmd` and used it to start processing each of the 5 files with meaningful data.

The end result is 3 separate output files in three separate directories: `./Output/PostZooniverse/Consensus/Correct` contains files for which there was a single consensus species ID per subject_id `.Output/PostZooniverse/Consensus/Needs check` contains files for which there was not consensus of at least 80% agreement on the species_ID

`.Output/PostZooniverse/Consensus/Needs check/Checklists` contains files that have been reduced to a single row per ambiguous subject and that have a final species ID column. These files can be opened in Excel and filled in with final species ID when going through images.

After exporting the checklists that need to be checked, I also went through the cleaned classifications and grabbed all of the cases for which the propotion of the vote for a particular species was \>= 0.8 and created a new dataframe called Assigned that grabbed a single row for each subject_id and assigned all of the relevant information. Then wrote that file to `./Output/PostZooniverse/Consensus/Correct/Assigned`.

In theory, the subject IDs from the checklist file and the subject ids from the assigned file should add up to all subject ids from the classification file.

When they don't match, I created a DF called LastOnes in the `3.determine_consensus_picks.Rmd` script that shows the data for those subject_IDs that were somehow left out. I need to dig in and figure out how those were missed. In the meantime, I am exporting the "Last Ones" .csv to `./Output/PostZooniverse/Consensus/Needs check/Last Ones`

### Finalizing consensus picks

It is up to a human to go through the (up to) 2 files with inconclusive species identifications to make the final species confirmation by looking back at the acutal images. The finalized checklist and Last Ones csv files should be saved to `./Output/PostZooniverse/Consensus/By workflow/` directory in a unique directory for each workflow number and version. The final assigned csv should be copied to this folder as well.
