---
title: "R Notebook"
output: html_notebook
---
## Introduction
Classification files that we download from the Zooniverse appear pretty straightforward at the outset, but the devil is in the details. There are several things that can be difficult to grasp at first:

1. What is the difference between a subject and a classification?
2. Why are there multiple instances of subjects and classifications?
3. Where the heck are the classifications? 
4. And what about all the metadata from the manifest?

This file is geared toward helping you understand how our classification files are organized so that you can understand what is happening (and why) when we start manipulating them.

A "real" classification file will have potentially more than 100,000 rows and running code can be a little slow. Here we will use a sample classification file that is a random selection of 1000 rows taken from one of the larger files.

## Set things up and pull in the data
```{r}
rm(list = ls())
library(here)
library(tidyverse)

myClass<-here("Data","PostZooniverse", "ClassificationFiles", "sample-classifications.csv")

myClass<-read.csv(myClass)

```



